language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - jruby-19mode # JRuby in 1.9 mode
script: bundle exec rspec spec
notifications:
  slack:
    rooms:
      - thekompanee:p46x27zMG89XW66DgGuutoaW#open-source
